api:
    resource: "@AppBundle/Controller/Api/v1"
    type:     annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
