# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.person:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - person_form                        # name of the form
            - person                             # alias of the form type
            - null                             # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [Default] } # validation groups

    app.form.type.person:
        class: AppBundle\Form\Type\PersonType
        tags:
        - { name: form.type, alias: person }

    app.form.company:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - company_form                        # name of the form
            - company                             # alias of the form type
            - null                             # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [Default] } # validation groups

    app.form.type.company:
        class: AppBundle\Form\Type\CompanyType
        tags:
        - { name: form.type, alias: company }

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    app.twig_extension.class:
        class: AppBundle\Twig\ClassTwigExtension
        public: false
        tags:
            - { name: twig.extension }

    app.twig_extension.bytes.class:
        class: AppBundle\Twig\FormatBytesExtension
        public: false
        tags:
            - { name: twig.extension }

    app.twig_extension.mention.class:
        class: AppBundle\Twig\DisplayUserExtenstion
        public: false
        tags:
            - { name: twig.extension }

    app.upload_listener:
        class: AppBundle\Event\Listener\UploadListener
        arguments:
            - @doctrine.orm.entity_manager
            - @security.context
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    app.comment.listener:
        class: AppBundle\Event\Listener\CommentListener
        arguments:
            - @fos_comment.manager.comment
            - @doctrine.orm.entity_manager
            - @hip_mandrill.dispatcher
            - @templating
        tags:
            - { name: kernel.event_listener, event: fos_comment.comment.post_persist, method: onCommentPersist}
            - { name: kernel.event_listener, event: fos_comment.comment.pre_persist, method: onCommentPrePersist}