<?php

namespace AppBundle\Entity\Repository;

use Pagerfanta\Adapter\DoctrineORMAdapter;
/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllQuery()
	{
		return $this->getEntityManager()
            ->createQuery('SELECT c FROM AppBundle:Company c ORDER BY c.name ASC');
	}

	public function findNum()
	{
		return $this->getEntityManager()
            ->createQuery('SELECT count(c) FROM AppBundle:Company c')
            ->getSingleResult()[1];
	}
}
