<?php

namespace AppBundle\Entity\Repository;

use Pagerfanta\Adapter\DoctrineORMAdapter;
use AppBundle\Entity\Tenant;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllQuery($tenantId)
	{
		return $this->getEntityManager()
            ->createQuery('SELECT c FROM AppBundle:Organization c where c.tenant = :tenant ORDER BY c.name ASC')
            ->setParameter('tenant', $tenantId);
	}

	public function findNum($tenantId)
	{
		return $this->getEntityManager()
            ->createQuery('SELECT count(c) FROM AppBundle:Organization c where c.tenant = :tenant')
            ->setParameter('tenant', $tenantId)
            ->getSingleResult()[1];
	}
}
