<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Tenant;
/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllQuery(Tenant $tenant)
	{
		return $this->getEntityManager()
            ->createQuery('SELECT c FROM AppBundle:Person c where c.tenant = :tenant ORDER BY c.lastname, c.firstname ASC')
            ->setParameter('tenant', $tenant->getId());
	}

	public function findNum(Tenant $tenant)
	{
		return $this->getEntityManager()
            ->createQuery('SELECT count(c) FROM AppBundle:Person c where c.tenant = :tenant')
            ->setParameter('tenant', $tenant->getId())
            ->getSingleResult()[1];
	}
}
