services:
    app.upload_listener:
        class: AppBundle\Event\Listener\UploadListener
        arguments:
            - @doctrine.orm.entity_manager
            - @security.token_storage
            - @multi_tenant.helper
            - %kernel.root_dir%
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    app.comment.listener:
        class: AppBundle\Event\Listener\CommentListener
        arguments:
            - @fos_comment.manager.comment
            - @doctrine.orm.entity_manager
            - @hip_mandrill.dispatcher
            - @templating
        tags:
            - { name: kernel.event_listener, event: fos_comment.comment.pre_persist, method: onCommentPersist}
            - { name: kernel.event_listener, event: fos_comment.comment.pre_persist, method: onCommentPrePersist}

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
