services:
    app.form.tenant_registration:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - tenant_user_registration_form                        # name of the form
            - tenant_user_registration                             # alias of the form type
            - null                             # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [Default] } # validation groups

    app.form.type.tenant_registration:
        class: AppBundle\Form\Type\TenantRegistrationType
        tags:
            - { name: form.type, alias: tenant_user_registration }

    app.form.person:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - person_form                        # name of the form
            - person                             # alias of the form type
            - null                             # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [Default] } # validation groups

    app.form.type.person:
        class: AppBundle\Form\Type\PersonType
        tags:
        - { name: form.type, alias: person }

    app.form.company:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - company_form                        # name of the form
            - company                             # alias of the form type
            - null                             # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [Default] } # validation groups

    app.form.type.company:
        class: AppBundle\Form\Type\CompanyType
        tags:
        - { name: form.type, alias: company }