parameters:
    app.entity.invitation.class: "AppBundle\\Entity\\Invitation"
    app.entity.file.class: "AppBundle\\Entity\\File"
    app.entity.person.class: "AppBundle\\Entity\\Person"
    app.entity.organization.class: "AppBundle\\Entity\\Organization"

services:
    app.hip_mandrill.message:
        class: "Hip\\MandrillBundle\\Message"

    app.fosuserbundlemandrillmailer:
         class: "AppBundle\\Mailer\\FOSUserBundleMailer"
         arguments:
             - "@router"
             - "@templating"
             - "@hip_mandrill.dispatcher"
             - "@app.hip_mandrill.message"
             - { confirmation.template: "%fos_user.registration.confirmation.template%", resetting_password.template: "%fos_user.resetting.email.template%" }

    fos_user.doctrine_registry:
        alias: doctrine

    app.apache_tika:
        class: "Enzim\\Lib\\TikaWrapper\\TikaWrapper"

    app.manager.organization:
        class: "AppBundle\\Entity\Manager\\OrganizationManager"
        arguments:
          - "@event_dispatcher"
          - "@doctrine.orm.entity_manager"
          - "%app.entity.organization.class%"

    app.manager.person:
        class: "AppBundle\\Entity\\Manager\\PersonManager"
        arguments:
          - "@event_dispatcher"
          - "@doctrine.orm.entity_manager"
          - "%app.entity.person.class%"

    app.manager.invitation:
        class: "AppBundle\\Entity\\Manager\\InvitationManager"
        arguments:
            - "@event_dispatcher"
            - "@doctrine.orm.entity_manager"
            - "%app.entity.invitation.class%"

    app.manager.file:
        class: "AppBundle\\Entity\\Manager\\FileManager"
        arguments:
            - "@event_dispatcher"
            - "@doctrine.orm.entity_manager"
            - "%app.entity.file.class%"
            - "@stof_doctrine_extensions.uploadable.manager"

    app.transformer_factory:
        class: "AppBundle\\Response\\TransformerFactory"
        arguments:
            - "@router"

    app.rest_response:
        class: "AppBundle\\Response\\RestResponse"
        arguments:
            - "@app.transformer_factory"

    validator.file.not_exist:
        class: AppBundle\Validator\Constraints\FileNotExistValidator
        arguments: ["@app.manager.file"]
        tags:
            - { name: validator.constraint_validator, alias: file_not_exist }

    app.request.validator:
        abstract:  true
        arguments: ["@validator"]

    app.validator.organization:
        class:  "AppBundle\\Request\\Validator\\OrganizationValidator"
        parent: "app.request.validator"

    app.annotation.controller:
        class: AppBundle\Annotation\Driver\ControllerAnnotationDriver
        tags: [{name: kernel.event_listener, event: kernel.controller, method: onKernelController}]
        arguments: [@annotation_reader]
