services:
    app.twig_extension.class:
        class: AppBundle\Twig\ClassTwigExtension
        public: false
        tags:
            - { name: twig.extension }

    app.twig_extension.bytes.class:
        class: AppBundle\Twig\FormatBytesExtension
        public: false
        tags:
            - { name: twig.extension }

    app.twig_extension.mention.class:
        class: AppBundle\Twig\DisplayUserExtenstion
        public: false
        tags:
            - { name: twig.extension }